"use client";

/**
 * 客户端统一搜索索引项
 */
export interface UnifiedSearchItem {
  id: string;
  title: string;
  content: string;
  type: "node" | "intel" | "tool" | "pitfall";
  typeLabel: string;
  url: string;
  tags?: string[];
  category?: string;
}

/**
 * 模块类型配置
 */
export const MODULE_CONFIG = {
  node: {
    label: "路线图",
    icon: "🗺️",
    color: "text-green-400",
    bgColor: "bg-green-400/10",
    borderColor: "border-green-400/30",
  },
  intel: {
    label: "情报",
    icon: "📰",
    color: "text-cyan-400",
    bgColor: "bg-cyan-400/10",
    borderColor: "border-cyan-400/30",
  },
  tool: {
    label: "工具",
    icon: "🔧",
    color: "text-amber-400",
    bgColor: "bg-amber-400/10",
    borderColor: "border-amber-400/30",
  },
  pitfall: {
    label: "踩坑",
    icon: "⚠️",
    color: "text-red-400",
    bgColor: "bg-red-400/10",
    borderColor: "border-red-400/30",
  },
} as const;

/**
 * 静态搜索数据 - 从各模块预编译
 * 这些数据会在构建时生成，客户端直接使用
 */
export const STATIC_SEARCH_INDEX: UnifiedSearchItem[] = [
  // 路由图节点
  {
    id: "node-linux-basic",
    title: "Linux 系统基础",
    content: "掌握 Linux 命令行、文件系统、权限管理、进程管理等基础知识",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["devops", "linux"],
    category: "devops",
  },
  {
    id: "node-git-github",
    title: "Git & GitHub 协作",
    content: "版本控制、分支管理、代码审查、开源协作工作流",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["devops", "git"],
    category: "devops",
  },
  {
    id: "node-docker-basic",
    title: "Docker 容器化",
    content: "容器技术、镜像构建、Docker Compose、容器编排",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["devops", "docker"],
    category: "devops",
  },
  {
    id: "node-math-linear-algebra",
    title: "线性代数",
    content: "矩阵运算、向量空间、特征值分解、SVD 分解",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["math", "linear-algebra"],
    category: "math",
  },
  {
    id: "node-math-probability",
    title: "概率与统计",
    content: "概率分布、贝叶斯定理、假设检验、回归分析",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["math", "probability"],
    category: "math",
  },
  {
    id: "node-pytorch-core",
    title: "PyTorch 框架",
    content: "张量操作、自动求导、神经网络构建、模型训练",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["cv", "pytorch", "deep-learning"],
    category: "cv",
  },
  {
    id: "node-cv-cnn",
    title: "CNN 经典架构",
    content: "卷积神经网络、ResNet、VGG、图像分类",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["cv", "cnn", "image-classification"],
    category: "cv",
  },
  {
    id: "node-cv-detection",
    title: "目标检测",
    content: "YOLO、SSD、Faster R-CNN、边界框回归",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["cv", "detection", "yolo"],
    category: "cv",
  },
  {
    id: "node-nlp-rnn",
    title: "NLP 基础与 RNN",
    content: "循环神经网络、LSTM、GRU、序列建模",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["nlp", "rnn", "sequence"],
    category: "nlp",
  },
  {
    id: "node-nlp-transformer",
    title: "Transformer 与预训练模型",
    content: "自注意力机制、BERT、GPT、预训练微调",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["nlp", "transformer", "bert", "gpt"],
    category: "nlp",
  },
  {
    id: "node-llm-finetune",
    title: "LLM 微调与对齐",
    content: "LoRA、QLoRA、RLHF、PPO、大语言模型训练",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["nlp", "llm", "finetune", "lora"],
    category: "nlp",
  },
  {
    id: "node-project-capstone",
    title: "综合实战项目",
    content: "端到端项目、竞赛实战、开源贡献、作品集",
    type: "node",
    typeLabel: "路线图",
    url: "/roadmap",
    tags: ["project", "capstone"],
    category: "project",
  },

  // 技术情报
  {
    id: "intel-001-transformer",
    title: "Transformer 架构详解",
    content: "Attention Is All You Need 论文解读，自注意力机制原理，位置编码，多头注意力",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/001-transformer",
    tags: ["transformer", "attention", "nlp"],
    category: "NLP",
  },
  {
    id: "intel-002-yolo",
    title: "YOLO 目标检测",
    content: "YOLOv1 到 YOLOv8 演进，实时目标检测原理，Anchor-Free 设计",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/002-yolo",
    tags: ["yolo", "detection", "cv"],
    category: "CV",
  },
  {
    id: "intel-003-lora-qlora",
    title: "LoRA/QLoRA 微调",
    content: "低秩适应原理，4-bit 量化微调，参数高效微调方法",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/003-lora-qlora",
    tags: ["lora", "qlora", "finetune", "llm"],
    category: "NLP",
  },
  {
    id: "intel-004-resnet",
    title: "ResNet 残差网络",
    content: "残差连接原理，梯度消失问题解决，深度网络训练技巧",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/004-resnet",
    tags: ["resnet", "cnn", "cv"],
    category: "CV",
  },
  {
    id: "intel-005-rag",
    title: "RAG 检索增强生成",
    content: "检索增强生成架构，向量数据库，Embedding 模型，知识库问答",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/005-rag",
    tags: ["rag", "retrieval", "llm"],
    category: "NLP",
  },
  {
    id: "intel-006-cnn-basics",
    title: "CNN 基础",
    content: "卷积层、池化层、全连接层，卷积神经网络基础原理",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/006-cnn-basics",
    tags: ["cnn", "convolution", "cv"],
    category: "CV",
  },
  {
    id: "intel-007-docker",
    title: "Docker 容器化",
    content: "Dockerfile 编写，镜像构建，容器编排，Docker Compose",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/007-docker",
    tags: ["docker", "container", "devops"],
    category: "DevOps",
  },
  {
    id: "intel-008-git",
    title: "Git 版本控制",
    content: "Git 工作流，分支策略，代码审查，开源协作",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/008-git",
    tags: ["git", "github", "devops"],
    category: "DevOps",
  },
  {
    id: "intel-009-linux",
    title: "Linux 系统",
    content: "Linux 命令行，Shell 脚本，系统管理，服务器配置",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/009-linux",
    tags: ["linux", "shell", "devops"],
    category: "DevOps",
  },
  {
    id: "intel-010-numpy-pandas",
    title: "NumPy/Pandas",
    content: "数值计算，数据处理，DataFrame 操作，数据分析",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/010-numpy-pandas",
    tags: ["numpy", "pandas", "data"],
    category: "Data",
  },
  {
    id: "intel-011-pytorch",
    title: "PyTorch 框架",
    content: "张量操作，自动求导，模型训练，GPU 加速",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/011-pytorch",
    tags: ["pytorch", "deep-learning"],
    category: "Framework",
  },
  {
    id: "intel-012-streamlit",
    title: "Streamlit",
    content: "快速构建数据应用，Web UI，模型演示",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/012-streamlit",
    tags: ["streamlit", "web", "demo"],
    category: "Tool",
  },
  {
    id: "intel-013-huggingface-datasets",
    title: "HuggingFace Datasets",
    content: "数据集加载，数据处理，HuggingFace 生态",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/013-huggingface-datasets",
    tags: ["huggingface", "datasets", "nlp"],
    category: "Data",
  },
  {
    id: "intel-014-onnx",
    title: "ONNX 部署",
    content: "模型导出，ONNX Runtime，跨平台部署",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/014-onnx",
    tags: ["onnx", "deployment", "inference"],
    category: "Deployment",
  },
  {
    id: "intel-015-rlhf",
    title: "RLHF 对齐",
    content: "人类反馈强化学习，PPO 算法，模型对齐",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/015-rlhf",
    tags: ["rlhf", "alignment", "llm"],
    category: "NLP",
  },
  {
    id: "intel-016-server-setup",
    title: "服务器配置",
    content: "GPU 服务器，深度学习环境配置，SSH 远程开发",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/016-server-setup",
    tags: ["server", "gpu", "devops"],
    category: "DevOps",
  },
  {
    id: "intel-017-metrics",
    title: "评估指标",
    content: "准确率、召回率、F1、mAP、AUC 等模型评估指标",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/017-metrics",
    tags: ["metrics", "evaluation"],
    category: "ML",
  },
  {
    id: "intel-018-mlflow",
    title: "MLflow 实验管理",
    content: "实验追踪，模型版本管理，MLflow 使用指南",
    type: "intel",
    typeLabel: "情报",
    url: "/intel/018-mlflow",
    tags: ["mlflow", "experiment", "mlops"],
    category: "MLOps",
  },

  // 工具
  {
    id: "tool-pytorch",
    title: "PyTorch",
    content: "深度学习框架，动态计算图，Python 优先，研究友好",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/pytorch",
    tags: ["deep-learning", "framework"],
    category: "框架",
  },
  {
    id: "tool-tensorflow",
    title: "TensorFlow",
    content: "Google 深度学习框架，生产部署，TF Serving",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/tensorflow",
    tags: ["deep-learning", "framework"],
    category: "框架",
  },
  {
    id: "tool-huggingface-transformers",
    title: "Hugging Face Transformers",
    content: "预训练模型库，NLP 工具链，Model Hub",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/huggingface-transformers",
    tags: ["nlp", "transformers"],
    category: "NLP",
  },
  {
    id: "tool-ultralytics-yolo",
    title: "Ultralytics YOLO",
    content: "实时目标检测，YOLOv8，易用 API",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/ultralytics-yolo",
    tags: ["detection", "yolo", "cv"],
    category: "CV",
  },
  {
    id: "tool-langchain",
    title: "LangChain",
    content: "LLM 应用开发框架，链式调用，Agent 构建",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/langchain",
    tags: ["llm", "chain", "agent"],
    category: "LLM",
  },
  {
    id: "tool-docker",
    title: "Docker",
    content: "容器化平台，环境隔离，快速部署",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/docker",
    tags: ["container", "devops"],
    category: "DevOps",
  },
  {
    id: "tool-git",
    title: "Git",
    content: "版本控制系统，分支管理，协作开发",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/git",
    tags: ["version-control", "devops"],
    category: "DevOps",
  },
  {
    id: "tool-onnx-runtime",
    title: "ONNX Runtime",
    content: "跨平台推理引擎，模型优化，高性能部署",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/onnx-runtime",
    tags: ["inference", "deployment"],
    category: "部署",
  },
  {
    id: "tool-streamlit",
    title: "Streamlit",
    content: "快速构建数据应用，Python Web UI",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/streamlit",
    tags: ["web", "demo"],
    category: "应用",
  },
  {
    id: "tool-gradio",
    title: "Gradio",
    content: "机器学习模型演示，快速构建交互界面",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/gradio",
    tags: ["demo", "ui"],
    category: "应用",
  },
  {
    id: "tool-mlflow",
    title: "MLflow",
    content: "实验追踪，模型管理，MLOps 平台",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/mlflow",
    tags: ["experiment", "mlops"],
    category: "MLOps",
  },
  {
    id: "tool-weights-biases",
    title: "Weights & Biases",
    content: "实验追踪，可视化，团队协作",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/weights-biases",
    tags: ["experiment", "visualization"],
    category: "MLOps",
  },
  {
    id: "tool-cuda",
    title: "CUDA",
    content: "NVIDIA GPU 并行计算，深度学习加速",
    type: "tool",
    typeLabel: "工具",
    url: "/toolbox/cuda",
    tags: ["gpu", "parallel"],
    category: "底层",
  },

  // 踩坑指南
  {
    id: "pitfall-cuda-out-of-memory",
    title: "CUDA 内存不足",
    content: "OOM 错误，显存溢出，减小 batch size，梯度累积",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["cuda", "memory", "gpu"],
    category: "GPU",
  },
  {
    id: "pitfall-import-error",
    title: "导入错误",
    content: "ModuleNotFoundError，版本冲突，环境配置问题",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["import", "python", "environment"],
    category: "Python",
  },
  {
    id: "pitfall-shape-mismatch",
    title: "张量形状不匹配",
    content: "维度错误，reshape，transpose，广播机制",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["tensor", "shape", "pytorch"],
    category: "PyTorch",
  },
  {
    id: "pitfall-gradient-vanishing",
    title: "梯度消失/爆炸",
    content: "梯度裁剪，残差连接，BatchNorm，学习率调整",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["gradient", "training"],
    category: "训练",
  },
  {
    id: "pitfall-data-loading",
    title: "数据加载慢",
    content: "DataLoader，num_workers，pin_memory，预加载",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["dataloader", "performance"],
    category: "性能",
  },
  {
    id: "pitfall-docker-network",
    title: "Docker 网络问题",
    content: "端口映射，容器通信，网络模式",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["docker", "network"],
    category: "Docker",
  },
  {
    id: "pitfall-git-conflict",
    title: "Git 合并冲突",
    content: "冲突解决，rebase vs merge，分支策略",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["git", "conflict"],
    category: "Git",
  },
  {
    id: "pitfall-version-compatibility",
    title: "版本兼容性问题",
    content: "CUDA 版本，PyTorch 版本，驱动兼容",
    type: "pitfall",
    typeLabel: "踩坑",
    url: "/pitfall",
    tags: ["version", "compatibility"],
    category: "环境",
  },
];
