// lib/constants.ts - 共享常量

// ============ 路线图 Track 颜色定义 ============

export type TrackId = "cv" | "nlp" | "llm" | "devops" | "math" | "project" | "cs" | "embedded" | "electronics" | "signals" | "control" | "electrical";

export interface TrackColors {
  text: string;           // 文本颜色类 e.g. "text-sky-400"
  bg: string;             // 背景颜色类 e.g. "bg-sky-400/10"
  border: string;         // 边框颜色类 e.g. "border-sky-400/30"
  solid: string;          // 实心背景类 e.g. "bg-sky-400"
  swimlane: string;       // 泳道背景 rgba e.g. "rgba(56, 189, 248, 0.06)"
  swimlaneBorder: string; // 泳道边框 rgba e.g. "rgba(56, 189, 248, 0.15)"
  label: string;          // 显示名称 e.g. "DevOps"
}

export const TRACK_COLORS: Record<TrackId, TrackColors> = {
  cv: {
    text: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/30",
    solid: "bg-orange-400",
    swimlane: "rgba(251, 146, 60, 0.06)",
    swimlaneBorder: "rgba(251, 146, 60, 0.15)",
    label: "CV",
  },
  nlp: {
    text: "text-violet-400",
    bg: "bg-violet-400/10",
    border: "border-violet-400/30",
    solid: "bg-violet-400",
    swimlane: "rgba(167, 139, 250, 0.06)",
    swimlaneBorder: "rgba(167, 139, 250, 0.15)",
    label: "NLP",
  },
  llm: {
    text: "text-fuchsia-400",
    bg: "bg-fuchsia-400/10",
    border: "border-fuchsia-400/30",
    solid: "bg-fuchsia-400",
    swimlane: "rgba(232, 121, 249, 0.06)",
    swimlaneBorder: "rgba(232, 121, 249, 0.15)",
    label: "LLM",
  },
  devops: {
    text: "text-sky-400",
    bg: "bg-sky-400/10",
    border: "border-sky-400/30",
    solid: "bg-sky-400",
    swimlane: "rgba(56, 189, 248, 0.06)",
    swimlaneBorder: "rgba(56, 189, 248, 0.15)",
    label: "DevOps",
  },
  math: {
    text: "text-emerald-400",
    bg: "bg-emerald-400/10",
    border: "border-emerald-400/30",
    solid: "bg-emerald-400",
    swimlane: "rgba(52, 211, 153, 0.06)",
    swimlaneBorder: "rgba(52, 211, 153, 0.15)",
    label: "数学",
  },
  project: {
    text: "text-pink-400",
    bg: "bg-pink-400/10",
    border: "border-pink-400/30",
    solid: "bg-pink-400",
    swimlane: "rgba(244, 114, 182, 0.06)",
    swimlaneBorder: "rgba(244, 114, 182, 0.15)",
    label: "项目",
  },
  cs: {
    text: "text-blue-500",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    solid: "bg-blue-500",
    swimlane: "rgba(59, 130, 246, 0.06)",
    swimlaneBorder: "rgba(59, 130, 246, 0.15)",
    label: "CS",
  },
  embedded: {
    text: "text-green-500",
    bg: "bg-green-500/10",
    border: "border-green-500/30",
    solid: "bg-green-500",
    swimlane: "rgba(34, 197, 94, 0.06)",
    swimlaneBorder: "rgba(34, 197, 94, 0.15)",
    label: "嵌入式",
  },
  electronics: {
    text: "text-yellow-500",
    bg: "bg-yellow-500/10",
    border: "border-yellow-500/30",
    solid: "bg-yellow-500",
    swimlane: "rgba(234, 179, 8, 0.06)",
    swimlaneBorder: "rgba(234, 179, 8, 0.15)",
    label: "电子",
  },
  signals: {
    text: "text-red-500",
    bg: "bg-red-500/10",
    border: "border-red-500/30",
    solid: "bg-red-500",
    swimlane: "rgba(239, 68, 68, 0.06)",
    swimlaneBorder: "rgba(239, 68, 68, 0.15)",
    label: "通信",
  },
  control: {
    text: "text-purple-500",
    bg: "bg-purple-500/10",
    border: "border-purple-500/30",
    solid: "bg-purple-500",
    swimlane: "rgba(168, 85, 247, 0.06)",
    swimlaneBorder: "rgba(168, 85, 247, 0.15)",
    label: "控制",
  },
  electrical: {
    text: "text-cyan-500",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    solid: "bg-cyan-500",
    swimlane: "rgba(6, 182, 212, 0.06)",
    swimlaneBorder: "rgba(6, 182, 212, 0.15)",
    label: "电气",
  },
};

// 便捷函数：获取 track 的完整样式字符串
export function getTrackColorClasses(track: TrackId): string {
  const colors = TRACK_COLORS[track];
  return `${colors.text} ${colors.bg} ${colors.border}`;
}

// 便捷函数：获取泳道标签颜色（从边框颜色派生）
export function getSwimlaneLabelColor(track: TrackId): string {
  const border = TRACK_COLORS[track].swimlaneBorder;
  // 将边框颜色的 alpha 从 0.15 改为 0.8 用于标签
  return border.replace(/[\d.]+\)$/, "0.8)");
}

// ============ 情报链接映射 ============

export const INTEL_LINKS: Record<string, string> = {
  "001-transformer": "Transformer 架构详解",
  "002-yolo": "YOLO 目标检测",
  "003-lora-qlora": "LoRA/QLoRA 微调",
  "004-resnet": "ResNet 残差网络",
  "005-rag": "RAG 检索增强生成",
  "006-cnn-basics": "CNN 基础",
  "007-docker": "Docker 容器化",
  "008-git": "Git 版本控制",
  "009-linux": "Linux 系统",
  "010-numpy-pandas": "NumPy/Pandas",
  "011-pytorch": "PyTorch 框架",
  "012-streamlit": "Streamlit",
  "013-huggingface-datasets": "HuggingFace Datasets",
  "014-onnx": "ONNX 部署",
  "015-cv-tricks": "CV 训练调优技巧",
  "015-rlhf": "RLHF 对齐",
  "016-server-setup": "服务器配置",
  "017-metrics": "评估指标",
  "018-mlflow": "MLflow 实验管理",
  "019-vllm-inference": "vLLM 推理优化",
  "020-prompt-engineering": "提示工程",
  "021-kubernetes": "Kubernetes",
  "022-prometheus-grafana": "Prometheus + Grafana",
  "023-data-pipeline-etl": "数据管道 ETL",
  "024-information-theory": "信息论基础",
  "025-convex-optimization": "凸优化理论",
  "026-onnx-deployment": "ONNX 部署实战",
  "027-rlhf-alignment": "RLHF 对齐详解",
  "028-server-ops": "服务器运维",
  "029-moe-mixture-of-experts": "MoE 混合专家",
  "030-multimodal-llm": "多模态大模型",
  "031-agentic-ai": "Agentic AI",
  "032-model-quantization": "模型量化",
  "033-long-context-rope": "长上下文与 RoPE",
  "034-cuda-programming": "CUDA 编程",
  "035-advanced-rag": "高级 RAG 技术",
  "036-code-generation": "代码生成",
  "037-distributed-training": "分布式训练",
  "038-llm-security": "LLM 安全",
  "039-model-evaluation": "模型评估",
  "040-data-annotation": "数据标注",
  "041-lora-finetuning": "LoRA 微调实战",
  "042-vector-database": "向量数据库",
  "043-mlops-engineering": "MLOps 工程",
  "050-cs-algo": "算法与数据结构",
  "051-cs-os": "操作系统原理",
  "052-embedded-c": "C语言与指针",
  "053-embedded-rtos": "RTOS 实时操作系统",
  "054-elec-circuit": "电路基础与模拟电子",
  "055-elec-signals": "信号与系统",
  "056-signals-comm": "通信原理",
  "057-ctrl-pid": "自动控制原理",
  "058-ctrl-ros": "机器人技术与 ROS2",
  "059-elec-motor": "电机控制与电力电子",
  "060-cv-instance-segmentation": "实例分割",
  "061-cv-pose-estimation": "人体姿态估计",
  "062-cv-ocr": "OCR 文字识别",
  "063-cv-diffusion": "扩散模型与图像生成",
  "064-nlp-rnn": "NLP 基础与 RNN",
  "065-llm-inference-optimization": "LLM 推理优化",
  "066-signals-basics": "信号基础",
  "067-signals-filter-design": "滤波器设计",
  "068-ctrl-state-space": "状态空间分析",
  "069-embedded-arduino": "Arduino 入门",
  "070-elec-components": "电子元器件",
  "071-elec-power-systems": "电力系统基础",
  "072-math-linear-algebra": "线性代数",
  "073-math-probability": "概率与统计",
  "074-math-tensor-ops": "张量运算",
  "075-cs-network": "计算机网络",
  "076-cs-database": "数据库系统",
  "077-embedded-driver": "嵌入式驱动开发",
  "078-embedded-hal": "嵌入式硬件抽象层",
  "079-elec-digital": "数字电子技术",
  "080-elec-pcb": "PCB 设计基础",
  "081-signals-dsp": "DSP 数字信号处理",
  "082-signals-wireless": "无线通信技术",
  "083-ctrl-plc": "PLC 工业控制",
  "084-ctrl-servo": "伺服控制系统",
  "085-electrical-safety": "电气安全与保护",
  "112-rl-basics": "强化学习基础",
  "113-gnn-basics": "图神经网络基础",
  "114-asr-speech-recognition": "语音识别",
  "115-tts-speech-synthesis": "语音合成",
  "116-recommender-systems": "推荐系统",
  "117-time-series": "时间序列分析",
  "118-anomaly-detection": "异常检测",
  "119-knowledge-graph": "知识图谱",
  "120-3d-point-cloud": "3D 点云",
  "121-object-tracking": "目标跟踪",
  "122-federated-learning": "联邦学习",
  "123-automl": "AutoML",
  "021-rag-intro": "RAG 入门",
  "022-agent-intro": "Agent 入门",
  "097-pitfall-embedded": "嵌入式开发踩坑",
  "098-pitfall-hardware": "硬件设计踩坑",
  "107-pitfall-db": "数据库踩坑",
  "108-pitfall-network": "网络踩坑",
  "110-pitfall-control": "控制踩坑",
  "111-pitfall-circuit": "电路踩坑",
  "133-pitfall-algorithm": "算法踩坑",
  "140-pitfall-c-pointer-out-of-bounds": "C 指针越界踩坑",
  "142-pitfall-pid-tuning-oscillation": "PID 调参振荡踩坑",
  "143-pitfall-fft-spectral-leakage": "FFT 频谱泄漏踩坑",
  "144-pitfall-h-bridge-shoot-through": "H 桥直通短路踩坑",
};

// ============ 工具链接映射 ============

export const TOOL_LINKS: Record<string, string> = {
  "airflow": "Apache Airflow",
  "altium-designer": "Altium Designer",
  "autocad-electrical": "AutoCAD Electrical",
  "chromadb": "ChromaDB",
  "codesys": "Codesys",
  "dask": "Dask",
  "docker": "Docker",
  "dvc": "DVC (Data Version Control)",
  "esp-idf": "ESP-IDF",
  "faiss": "FAISS",
  "fastapi": "FastAPI",
  "freertos": "FreeRTOS",
  "gcc": "GCC",
  "git": "Git",
  "gradio": "Gradio",
  "grafana": "Grafana",
  "huggingface-transformers": "Hugging Face Transformers",
  "jupyter": "Jupyter Notebook",
  "kicad": "KiCad",
  "kubeflow": "Kubeflow",
  "kubernetes": "Kubernetes",
  "label-studio": "Label Studio",
  "langchain": "LangChain",
  "lightgbm": "LightGBM",
  "ltspice": "LTspice",
  "matlab": "MATLAB",
  "matplotlib": "Matplotlib",
  "mlflow": "MLflow",
  "mysql": "MySQL",
  "numpy": "NumPy",
  "onnx-runtime": "ONNX Runtime",
  "opencv": "OpenCV",
  "pandas": "pandas",
  "pgvector": "pgvector + PostgreSQL",
  "plotly": "Plotly",
  "polars": "Polars",
  "postman": "Postman",
  "prometheus": "Prometheus",
  "pytorch": "PyTorch",
  "pytorch-geometric": "PyTorch Geometric",
  "pytorch-lightning": "PyTorch Lightning",
  "redis": "Redis",
  "ros2": "ROS2",
  "scikit-learn": "scikit-learn",
  "segment-anything": "Segment Anything",
  "spacy": "spaCy",
  "stable-baselines3": "Stable Baselines3",
  "stm32cubemx": "STM32CubeMX",
  "streamlit": "Streamlit",
  "tensorflow": "TensorFlow",
  "tia-portal": "TIA Portal",
  "transformers-agent": "Transformers Agent",
  "triton-inference-server": "Triton Inference Server",
  "ultralytics-yolo": "Ultralytics YOLO",
  "vllm": "vLLM",
  "vscode": "VS Code",
  "weights-and-biases": "Weights & Biases",
  "whisper": "Whisper",
  "wireshark": "Wireshark",
  "xgboost": "XGBoost",
};

// ============ 术语分类颜色 ============

export const CATEGORY_COLORS: Record<string, string> = {
  "ai-ml": "text-cyan-400 bg-cyan-400/10 border-cyan-400/30",
  "engineering": "text-amber-400 bg-amber-400/10 border-amber-400/30",
  "math": "text-emerald-400 bg-emerald-400/10 border-emerald-400/30",
  "project": "text-pink-400 bg-pink-400/10 border-pink-400/30",
};

// ============ 路线图节点名称映射 ============

export const NODE_NAMES: Record<string, string> = {
  // DevOps
  "linux-basic": "Linux 系统基础",
  "git-github": "Git & GitHub 协作",
  "docker-basic": "Docker 容器化",
  "devops-cicd": "CI/CD 与自动化部署",
  "devops-docker-api": "模型服务 Docker 化部署",
  "devops-kubernetes": "Kubernetes 容器编排",
  "devops-monitoring": "监控体系：Prometheus + Grafana",
  "devops-mlops": "MLOps 与模型运维",
  // Math
  "math-linear-algebra": "线性代数",
  "math-probability": "概率与统计",
  "math-tensor-ops": "PyTorch 张量运算",
  "math-information-theory": "信息论基础",
  "math-optimization": "凸优化理论基础",
  // CS
  "cs-algo": "算法与数据结构",
  "cs-os": "操作系统原理",
  "cs-network": "计算机网络",
  "cs-database": "数据库系统",
  // Embedded
  "embedded-c": "C语言与指针",
  "embedded-rtos": "RTOS 实时操作系统",
  "embedded-driver": "嵌入式驱动开发",
  "embedded-hal": "嵌入式硬件抽象层",
  // Electronics
  "elec-circuit": "电路基础与模拟电子",
  "elec-signals": "信号与系统",
  "elec-digital": "数字电子技术",
  "elec-pcb": "PCB 设计基础",
  "elec-fpga": "FPGA 与数字系统设计",
  // Signals
  "signals-basics": "信号与系统基础",
  "signals-comm": "通信原理",
  "signals-dsp": "DSP 数字信号处理",
  "signals-wireless": "无线通信技术",
  "signals-antenna": "天线原理与设计",
  // Control
  "ctrl-pid": "自动控制原理",
  "ctrl-ros": "机器人技术与 ROS2",
  "ctrl-plc": "PLC 工业控制",
  "ctrl-servo": "伺服控制系统",
  // Electrical
  "elec-motor": "电机控制与电力电子",
  "electrical-power-electronics": "电力电子技术",
  "electrical-power": "电力系统基础",
  "electrical-safety": "电气安全与保护",
  "electrical-relay": "继电保护与电力系统自动化",
  // CV
  "pytorch-core": "PyTorch 框架",
  "cv-cnn": "CNN 经典架构",
  "cv-detection": "目标检测",
  "cv-instance-segmentation": "YOLOv8-seg 实例分割实战",
  "cv-pose-estimation": "人体姿态估计",
  "cv-ocr": "OCR 文字识别",
  "cv-diffusion": "扩散模型与图像生成",
  // NLP
  "nlp-rnn": "NLP 基础与 RNN",
  "nlp-word-embeddings": "词向量与语义表示",
  "nlp-sentiment-analysis": "情感分析与文本分类",
  "nlp-sequence-labeling": "序列标注与信息抽取",
  "nlp-transformer": "Transformer 与预训练模型",
  "nlp-machine-translation": "机器翻译与文本生成",
  // LLM
  "llm-fundamentals": "LLM 基础原理",
  "llm-pretraining": "预训练与数据工程",
  "llm-finetune": "LLM 微调与对齐",
  "llm-rag": "RAG 检索增强生成",
  "llm-local-rag": "本地知识库 RAG 系统",
  "llm-inference": "LLM 推理加速与部署",
  "llm-prompt-engineering": "提示工程与 Agent 设计",
  "llm-agent": "Agent 与工具调用",
  "llm-evaluation": "LLM 评估与安全",
  // Project
  "project-cv-classification": "图像分类与模型部署",
  "project-rag-app": "RAG 知识库问答系统",
  "project-llm-agent": "LLM Agent 智能助手",
  "project-data-pipeline": "数据管道与 ETL",
  "project-iot-fastapi": "ESP32 传感器数据链路",
  "project-capstone": "综合实战项目",

};

// ============ 工具 ID 到名称映射 ============

export const TOOL_IDS: Record<string, string> = {
  "airflow": "Apache Airflow",
  "altium-designer": "Altium Designer",
  "autocad-electrical": "AutoCAD Electrical",
  "chromadb": "ChromaDB",
  "codesys": "Codesys",
  "dask": "Dask",
  "docker": "Docker",
  "dvc": "DVC (Data Version Control)",
  "esp-idf": "ESP-IDF",
  "faiss": "FAISS",
  "fastapi": "FastAPI",
  "freertos": "FreeRTOS",
  "gcc": "GCC",
  "git": "Git",
  "gradio": "Gradio",
  "grafana": "Grafana",
  "huggingface-transformers": "Hugging Face Transformers",
  "jupyter": "Jupyter Notebook",
  "kicad": "KiCad",
  "kubeflow": "Kubeflow",
  "kubernetes": "Kubernetes",
  "label-studio": "Label Studio",
  "langchain": "LangChain",
  "lightgbm": "LightGBM",
  "ltspice": "LTspice",
  "matlab": "MATLAB",
  "matplotlib": "Matplotlib",
  "mlflow": "MLflow",
  "mysql": "MySQL",
  "numpy": "NumPy",
  "onnx-runtime": "ONNX Runtime",
  "opencv": "OpenCV",
  "pandas": "pandas",
  "pgvector": "pgvector + PostgreSQL",
  "plotly": "Plotly",
  "polars": "Polars",
  "postman": "Postman",
  "prometheus": "Prometheus",
  "pytorch": "PyTorch",
  "pytorch-geometric": "PyTorch Geometric",
  "pytorch-lightning": "PyTorch Lightning",
  "redis": "Redis",
  "ros2": "ROS2",
  "scikit-learn": "scikit-learn",
  "segment-anything": "Segment Anything",
  "spacy": "spaCy",
  "stable-baselines3": "Stable Baselines3",
  "stm32cubemx": "STM32CubeMX",
  "streamlit": "Streamlit",
  "tensorflow": "TensorFlow",
  "tia-portal": "TIA Portal",
  "transformers-agent": "Transformers Agent",
  "triton-inference-server": "Triton Inference Server",
  "ultralytics-yolo": "Ultralytics YOLO",
  "vllm": "vLLM",
  "vscode": "VS Code",
  "weights-and-biases": "Weights & Biases",
  "whisper": "Whisper",
  "wireshark": "Wireshark",
  "xgboost": "XGBoost",
};
